### ISSUE TITLE
Permissions error on saving - WP 4.5.2, Multisite

### ISSUE THREAD

**Issue by pafro** [ContentLEAD/BraftonWordpressPlugin#65]
We're attempting to install the plugin (latest clone from github) on:
- WP 4.5.2
- Multisite Enabled
- **Multisite is in folder mode**, not sub domain
- Site owners unable to administrate Plugins, only network admins
- Plugin Version: 3.4.6
- Plugin enabled only on one site, not network activated.

And we're getting a 'You do not have sufficient permissions to access this page' error:

![image](https://cloud.githubusercontent.com/assets/6830529/15525351/d7b7a22a-226c-11e6-8732-cc6c45688a6a.png)

it occurs on all tabs for settings. The main Network Admin account is the admin account we are using, so there shouldn't be a error.

Any ideas?

**Comment by pafro** [comment]
Enabled Site owners to administrate plugins and attempted with a non network admin account  (standard admin account for that site) - same issue.

**Comment by pafro** [comment]
On closer inspection of the URL's used, it appears that it's dropping the subfolder name for the site:
`/charlie/wp-admin/admin.php?page=BraftonArticleLoader&tab=1`
on save will go to
`/wp-admin/admin.php?page=BraftonArticleLoader&tab=1`

Hence the permissions error.

**Comment by pafro** [comment]
Now confirmed this is the problem.  I used Chrome Dev Tools and changed the form action to include the site folder.

From:

![image](https://cloud.githubusercontent.com/assets/6830529/15526059/58477474-2272-11e6-903e-62c69b3dc4f5.png)

To:
![image](https://cloud.githubusercontent.com/assets/6830529/15526063/673df520-2272-11e6-82b7-7e3b638d47bf.png)

And it saved correctly.

**Comment by dking3876** [comment]
Thank you for your input.  We are able to see this issue as well in multisites and will be correcting it shortly with a patch in version 3.4.8

**Comment by pafro** [comment]
@dking3876 Any chance you've released this update yet?  Couldn't seem to track it down or see it in this repo.
